[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/demo.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
